export const themes = {
  "Scheme=STUDIO_MONITOR light": {
    surfaceVariant: "#e4e7ea",
    onBandMuted: "#7d858a",
    wordExtra: "#ea0010",
    wordMissed: "#737373",
    bandVariant: "#191c1f",
    onAccent: "#ffffff",
    error: "#a33a26",
    outline: "#8a8e91",
    band: "#0e1012",
    wordMatched: "#00863c",
    surface: "#ffffff",
    textSecondary: "#6b7276",
    wordPartial: "#9e6a00",
    accent: "#9a650f",
    textPrimary: "#1a1d20",
    background: "#f4f5f6",
    onBand: "#e8eaec",
    bandOutline: "#4a5054",
    outlineVariant: "#c9cdd0",
    page: "1120px",
    gap: "24px",
    corner: "12px",
    shadow: "0px 1px 2px 0px rgba(20, 23, 26, 0.05), 0px 12px 24px 0px rgba(20, 23, 26, 0.12)",
    measure: 66,
    type: {
      _96: "96px",
      _200: "200px",
      _18: "18px",
      _24: "24px",
      _22: "22px",
      _14: "14px",
      _12: "12px",
      _16: "16px",
      _32: "32px",
      _64: "64px",
      _40: "40px",
    },
    bodySmallRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.4286 },
    space: {
      _9: "9px",
      _11: "11px",
      _40: "40px",
      _4: "4px",
      _5: "5px",
      _20: "20px",
      _15: "15px",
      _8: "8px",
      _13: "13px",
      _2: "2px",
      _12: "12px",
    },
    bodySmallLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.7143 },
    size: {
      _72: "72px",
      _4: "4px",
      _150: "150px",
      _45: "45px",
      _20: "20px",
      _56: "56px",
      _48: "48px",
      _600: "600px",
      _12: "12px",
      _110: "110px",
      _64: "64px",
      _88: "88px",
      _70: "70px",
      _6: "6px",
      _60: "60px",
      _8: "8px",
      _160: "160px",
      _96: "96px",
      _80: "80px",
      _27: "27px",
      _42: "42px",
      _40: "40px",
      _16: "16px",
      _32: "32px",
      _200: "200px",
      _2: "2px",
      _340: "340px",
      _1: "1px",
      _24: "24px",
      _34: "34px",
      _28: "28px",
    },
    displayMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.25 },
    bodySmallTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.4286 },
    bodyLargeMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    bodyLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    displaySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.25 },
    bodyLargeRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    regular: { weight: 400, italic: false },
    share: {
      _100: 1,
      _75: 0.75,
      _66: 0.66,
      _25: 0.25,
      _33: 0.33,
      _50: 0.5,
    },
    strokeWide: "2px",
    spaceTiny: "4px",
    spaceSmall: "8px",
    mono: "\"IBM Plex Mono\"",
    glyphSmall: "20px",
    displayRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.25 },
    semiBold: { weight: 600, italic: false },
    tracking: "1.1px",
    shadowEdgeUp: "0px -1px 4px 0px rgba(0, 0, 0, 0.12)",
    spaceMicro: "2px",
    bodySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.5 },
    titleRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.2727 },
    bodySmallLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.7143 },
    shadowLift: "0px 4px 8px 0px rgba(0, 0, 0, 0.12)",
    scrim: "#000000",
    controlEdge: 3,
    glyph: "24px",
    wordState: 3,
    stroke: "1px",
    text: 4.5,
    heroSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "96px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    glyphHuge: "48px",
    labelTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.3333 },
    labelLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 2 },
    bodySmallSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.4286 },
    titleSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2727 },
    posterSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "64px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    veil: 0.35,
    bodyMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.5 },
    labelLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 2 },
    headlineRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    iconLayer: 3,
    family: "\"IBM Plex Sans\"",
    bodyRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.5 },
    headlineSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    radius: {
      _12: "12px",
      full: "999px",
      _4: "4px",
    },
    displayLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "40px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2 },
    spaceMedium: "12px",
    spaceBig: "20px",
    giantSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "200px", fontWeight: { weight: 600, italic: false }, lineHeight: 1 },
    highlight: 1.5,
    labelRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    titleMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.2727 },
    glyphBig: "32px",
    strokeBold: "4px",
    labelSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    bodySmallMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.4286 },
    connector: 0.55,
    headlineMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    ghost: 0.18,
    radiusRound: "999px",
    spaceSuperBig: "40px",
    medium: { weight: 500, italic: false },
    labelMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    link: {
      colour: "#9a650f",
    },
    library: {
      color: {
        link: "#9a650f",
      },
    },
  },
  "Scheme=STUDIO_MONITOR dark": {
    surfaceVariant: "#22262a",
    onBandMuted: "#7d858a",
    wordExtra: "#ea0010",
    wordMissed: "#737373",
    bandVariant: "#191c1f",
    onAccent: "#14171a",
    error: "#e3705b",
    outline: "#63696c",
    band: "#22262a",
    wordMatched: "#00863c",
    surface: "#191c1f",
    textSecondary: "#a0a7ad",
    wordPartial: "#9e6a00",
    accent: "#f2a93b",
    textPrimary: "#e8eaec",
    background: "#0e1012",
    onBand: "#e8eaec",
    bandOutline: "#4a5054",
    outlineVariant: "#4a5054",
    page: "1120px",
    gap: "24px",
    corner: "12px",
    shadow: "0px 1px 2px 0px rgba(20, 23, 26, 0.05), 0px 12px 24px 0px rgba(20, 23, 26, 0.12)",
    measure: 66,
    type: {
      _96: "96px",
      _200: "200px",
      _18: "18px",
      _24: "24px",
      _22: "22px",
      _14: "14px",
      _12: "12px",
      _16: "16px",
      _32: "32px",
      _64: "64px",
      _40: "40px",
    },
    bodySmallRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.4286 },
    space: {
      _9: "9px",
      _11: "11px",
      _40: "40px",
      _4: "4px",
      _5: "5px",
      _20: "20px",
      _15: "15px",
      _8: "8px",
      _13: "13px",
      _2: "2px",
      _12: "12px",
    },
    bodySmallLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.7143 },
    size: {
      _72: "72px",
      _4: "4px",
      _150: "150px",
      _45: "45px",
      _20: "20px",
      _56: "56px",
      _48: "48px",
      _600: "600px",
      _12: "12px",
      _110: "110px",
      _64: "64px",
      _88: "88px",
      _70: "70px",
      _6: "6px",
      _60: "60px",
      _8: "8px",
      _160: "160px",
      _96: "96px",
      _80: "80px",
      _27: "27px",
      _42: "42px",
      _40: "40px",
      _16: "16px",
      _32: "32px",
      _200: "200px",
      _2: "2px",
      _340: "340px",
      _1: "1px",
      _24: "24px",
      _34: "34px",
      _28: "28px",
    },
    displayMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.25 },
    bodySmallTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.4286 },
    bodyLargeMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    bodyLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    displaySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.25 },
    bodyLargeRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    regular: { weight: 400, italic: false },
    share: {
      _100: 1,
      _75: 0.75,
      _66: 0.66,
      _25: 0.25,
      _33: 0.33,
      _50: 0.5,
    },
    strokeWide: "2px",
    spaceTiny: "4px",
    spaceSmall: "8px",
    mono: "\"IBM Plex Mono\"",
    glyphSmall: "20px",
    displayRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.25 },
    semiBold: { weight: 600, italic: false },
    tracking: "1.1px",
    shadowEdgeUp: "0px -1px 4px 0px rgba(0, 0, 0, 0.12)",
    spaceMicro: "2px",
    bodySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.5 },
    titleRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.2727 },
    bodySmallLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.7143 },
    shadowLift: "0px 4px 8px 0px rgba(0, 0, 0, 0.12)",
    scrim: "#000000",
    controlEdge: 3,
    glyph: "24px",
    wordState: 3,
    stroke: "1px",
    text: 4.5,
    heroSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "96px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    glyphHuge: "48px",
    labelTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.3333 },
    labelLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 2 },
    bodySmallSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.4286 },
    titleSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2727 },
    posterSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "64px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    veil: 0.35,
    bodyMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.5 },
    labelLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 2 },
    headlineRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    iconLayer: 3,
    family: "\"IBM Plex Sans\"",
    bodyRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.5 },
    headlineSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    radius: {
      _12: "12px",
      full: "999px",
      _4: "4px",
    },
    displayLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "40px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2 },
    spaceMedium: "12px",
    spaceBig: "20px",
    giantSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "200px", fontWeight: { weight: 600, italic: false }, lineHeight: 1 },
    highlight: 1.5,
    labelRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    titleMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.2727 },
    glyphBig: "32px",
    strokeBold: "4px",
    labelSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    bodySmallMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.4286 },
    connector: 0.55,
    headlineMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    ghost: 0.18,
    radiusRound: "999px",
    spaceSuperBig: "40px",
    medium: { weight: 500, italic: false },
    labelMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    link: {
      colour: "#f2a93b",
    },
    library: {
      color: {
        link: "#9a650f",
      },
    },
  },
  "Scheme=PAPER_AND_INK light": {
    surfaceVariant: "#ebe4d8",
    onBandMuted: "#938576",
    wordExtra: "#a6432b",
    wordMissed: "#6f757c",
    bandVariant: "#201b16",
    onAccent: "#fffdf9",
    error: "#a6432b",
    outline: "#938b7f",
    band: "#17130f",
    wordMatched: "#2f6b44",
    surface: "#fffdf9",
    textSecondary: "#6b5f51",
    wordPartial: "#b37619",
    accent: "#2e4b7a",
    textPrimary: "#221c16",
    background: "#f7f3ec",
    onBand: "#f3ebe1",
    bandOutline: "#5a4e41",
    outlineVariant: "#d6ccbc",
    page: "1120px",
    gap: "24px",
    corner: "12px",
    shadow: "0px 1px 2px 0px rgba(20, 23, 26, 0.05), 0px 12px 24px 0px rgba(20, 23, 26, 0.12)",
    measure: 66,
    type: {
      _96: "96px",
      _200: "200px",
      _18: "18px",
      _24: "24px",
      _22: "22px",
      _14: "14px",
      _12: "12px",
      _16: "16px",
      _32: "32px",
      _64: "64px",
      _40: "40px",
    },
    bodySmallRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.4286 },
    space: {
      _9: "9px",
      _11: "11px",
      _40: "40px",
      _4: "4px",
      _5: "5px",
      _20: "20px",
      _15: "15px",
      _8: "8px",
      _13: "13px",
      _2: "2px",
      _12: "12px",
    },
    bodySmallLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.7143 },
    size: {
      _72: "72px",
      _4: "4px",
      _150: "150px",
      _45: "45px",
      _20: "20px",
      _56: "56px",
      _48: "48px",
      _600: "600px",
      _12: "12px",
      _110: "110px",
      _64: "64px",
      _88: "88px",
      _70: "70px",
      _6: "6px",
      _60: "60px",
      _8: "8px",
      _160: "160px",
      _96: "96px",
      _80: "80px",
      _27: "27px",
      _42: "42px",
      _40: "40px",
      _16: "16px",
      _32: "32px",
      _200: "200px",
      _2: "2px",
      _340: "340px",
      _1: "1px",
      _24: "24px",
      _34: "34px",
      _28: "28px",
    },
    displayMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.25 },
    bodySmallTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.4286 },
    bodyLargeMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    bodyLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    displaySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.25 },
    bodyLargeRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    regular: { weight: 400, italic: false },
    share: {
      _100: 1,
      _75: 0.75,
      _66: 0.66,
      _25: 0.25,
      _33: 0.33,
      _50: 0.5,
    },
    strokeWide: "2px",
    spaceTiny: "4px",
    spaceSmall: "8px",
    mono: "\"IBM Plex Mono\"",
    glyphSmall: "20px",
    displayRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.25 },
    semiBold: { weight: 600, italic: false },
    tracking: "1.1px",
    shadowEdgeUp: "0px -1px 4px 0px rgba(0, 0, 0, 0.12)",
    spaceMicro: "2px",
    bodySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.5 },
    titleRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.2727 },
    bodySmallLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.7143 },
    shadowLift: "0px 4px 8px 0px rgba(0, 0, 0, 0.12)",
    scrim: "#000000",
    controlEdge: 3,
    glyph: "24px",
    wordState: 3,
    stroke: "1px",
    text: 4.5,
    heroSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "96px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    glyphHuge: "48px",
    labelTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.3333 },
    labelLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 2 },
    bodySmallSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.4286 },
    titleSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2727 },
    posterSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "64px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    veil: 0.35,
    bodyMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.5 },
    labelLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 2 },
    headlineRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    iconLayer: 3,
    family: "\"IBM Plex Sans\"",
    bodyRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.5 },
    headlineSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    radius: {
      _12: "12px",
      full: "999px",
      _4: "4px",
    },
    displayLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "40px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2 },
    spaceMedium: "12px",
    spaceBig: "20px",
    giantSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "200px", fontWeight: { weight: 600, italic: false }, lineHeight: 1 },
    highlight: 1.5,
    labelRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    titleMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.2727 },
    glyphBig: "32px",
    strokeBold: "4px",
    labelSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    bodySmallMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.4286 },
    connector: 0.55,
    headlineMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    ghost: 0.18,
    radiusRound: "999px",
    spaceSuperBig: "40px",
    medium: { weight: 500, italic: false },
    labelMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    link: {
      colour: "#2e4b7a",
    },
    library: {
      color: {
        link: "#9a650f",
      },
    },
  },
  "Scheme=PAPER_AND_INK dark": {
    surfaceVariant: "#2c251e",
    onBandMuted: "#938576",
    wordExtra: "#e08e76",
    wordMissed: "#80868d",
    bandVariant: "#201b16",
    onAccent: "#161b24",
    error: "#e08e76",
    outline: "#716659",
    band: "#2c251e",
    wordMatched: "#7fc79a",
    surface: "#201b16",
    textSecondary: "#b9ac9c",
    wordPartial: "#f2a93b",
    accent: "#9fbee8",
    textPrimary: "#f3ebe1",
    background: "#17130f",
    onBand: "#f3ebe1",
    bandOutline: "#5a4e41",
    outlineVariant: "#5a4e41",
    page: "1120px",
    gap: "24px",
    corner: "12px",
    shadow: "0px 1px 2px 0px rgba(20, 23, 26, 0.05), 0px 12px 24px 0px rgba(20, 23, 26, 0.12)",
    measure: 66,
    type: {
      _96: "96px",
      _200: "200px",
      _18: "18px",
      _24: "24px",
      _22: "22px",
      _14: "14px",
      _12: "12px",
      _16: "16px",
      _32: "32px",
      _64: "64px",
      _40: "40px",
    },
    bodySmallRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.4286 },
    space: {
      _9: "9px",
      _11: "11px",
      _40: "40px",
      _4: "4px",
      _5: "5px",
      _20: "20px",
      _15: "15px",
      _8: "8px",
      _13: "13px",
      _2: "2px",
      _12: "12px",
    },
    bodySmallLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.7143 },
    size: {
      _72: "72px",
      _4: "4px",
      _150: "150px",
      _45: "45px",
      _20: "20px",
      _56: "56px",
      _48: "48px",
      _600: "600px",
      _12: "12px",
      _110: "110px",
      _64: "64px",
      _88: "88px",
      _70: "70px",
      _6: "6px",
      _60: "60px",
      _8: "8px",
      _160: "160px",
      _96: "96px",
      _80: "80px",
      _27: "27px",
      _42: "42px",
      _40: "40px",
      _16: "16px",
      _32: "32px",
      _200: "200px",
      _2: "2px",
      _340: "340px",
      _1: "1px",
      _24: "24px",
      _34: "34px",
      _28: "28px",
    },
    displayMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.25 },
    bodySmallTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.4286 },
    bodyLargeMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    bodyLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    displaySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.25 },
    bodyLargeRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    regular: { weight: 400, italic: false },
    share: {
      _100: 1,
      _75: 0.75,
      _66: 0.66,
      _25: 0.25,
      _33: 0.33,
      _50: 0.5,
    },
    strokeWide: "2px",
    spaceTiny: "4px",
    spaceSmall: "8px",
    mono: "\"IBM Plex Mono\"",
    glyphSmall: "20px",
    displayRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.25 },
    semiBold: { weight: 600, italic: false },
    tracking: "1.1px",
    shadowEdgeUp: "0px -1px 4px 0px rgba(0, 0, 0, 0.12)",
    spaceMicro: "2px",
    bodySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.5 },
    titleRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.2727 },
    bodySmallLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.7143 },
    shadowLift: "0px 4px 8px 0px rgba(0, 0, 0, 0.12)",
    scrim: "#000000",
    controlEdge: 3,
    glyph: "24px",
    wordState: 3,
    stroke: "1px",
    text: 4.5,
    heroSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "96px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    glyphHuge: "48px",
    labelTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.3333 },
    labelLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 2 },
    bodySmallSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.4286 },
    titleSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2727 },
    posterSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "64px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    veil: 0.35,
    bodyMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.5 },
    labelLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 2 },
    headlineRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    iconLayer: 3,
    family: "\"IBM Plex Sans\"",
    bodyRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.5 },
    headlineSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    radius: {
      _12: "12px",
      full: "999px",
      _4: "4px",
    },
    displayLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "40px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2 },
    spaceMedium: "12px",
    spaceBig: "20px",
    giantSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "200px", fontWeight: { weight: 600, italic: false }, lineHeight: 1 },
    highlight: 1.5,
    labelRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    titleMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.2727 },
    glyphBig: "32px",
    strokeBold: "4px",
    labelSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    bodySmallMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.4286 },
    connector: 0.55,
    headlineMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    ghost: 0.18,
    radiusRound: "999px",
    spaceSuperBig: "40px",
    medium: { weight: 500, italic: false },
    labelMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    link: {
      colour: "#9fbee8",
    },
    library: {
      color: {
        link: "#9a650f",
      },
    },
  },
  "Scheme=SIGNAL light": {
    surfaceVariant: "#e2eaef",
    onBandMuted: "#6f8494",
    wordExtra: "#b23a2b",
    wordMissed: "#6f757c",
    bandVariant: "#101820",
    onAccent: "#ffffff",
    error: "#b23a2b",
    outline: "#7f909d",
    band: "#0a0f14",
    wordMatched: "#2f8f5b",
    surface: "#ffffff",
    textSecondary: "#4a5d6b",
    wordPartial: "#8a5a00",
    accent: "#00695c",
    textPrimary: "#0a1219",
    background: "#f2f6f8",
    onBand: "#e6eef5",
    bandOutline: "#39505f",
    outlineVariant: "#a8bccb",
    page: "1120px",
    gap: "24px",
    corner: "12px",
    shadow: "0px 1px 2px 0px rgba(20, 23, 26, 0.05), 0px 12px 24px 0px rgba(20, 23, 26, 0.12)",
    measure: 66,
    type: {
      _96: "96px",
      _200: "200px",
      _18: "18px",
      _24: "24px",
      _22: "22px",
      _14: "14px",
      _12: "12px",
      _16: "16px",
      _32: "32px",
      _64: "64px",
      _40: "40px",
    },
    bodySmallRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.4286 },
    space: {
      _9: "9px",
      _11: "11px",
      _40: "40px",
      _4: "4px",
      _5: "5px",
      _20: "20px",
      _15: "15px",
      _8: "8px",
      _13: "13px",
      _2: "2px",
      _12: "12px",
    },
    bodySmallLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.7143 },
    size: {
      _72: "72px",
      _4: "4px",
      _150: "150px",
      _45: "45px",
      _20: "20px",
      _56: "56px",
      _48: "48px",
      _600: "600px",
      _12: "12px",
      _110: "110px",
      _64: "64px",
      _88: "88px",
      _70: "70px",
      _6: "6px",
      _60: "60px",
      _8: "8px",
      _160: "160px",
      _96: "96px",
      _80: "80px",
      _27: "27px",
      _42: "42px",
      _40: "40px",
      _16: "16px",
      _32: "32px",
      _200: "200px",
      _2: "2px",
      _340: "340px",
      _1: "1px",
      _24: "24px",
      _34: "34px",
      _28: "28px",
    },
    displayMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.25 },
    bodySmallTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.4286 },
    bodyLargeMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    bodyLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    displaySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.25 },
    bodyLargeRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    regular: { weight: 400, italic: false },
    share: {
      _100: 1,
      _75: 0.75,
      _66: 0.66,
      _25: 0.25,
      _33: 0.33,
      _50: 0.5,
    },
    strokeWide: "2px",
    spaceTiny: "4px",
    spaceSmall: "8px",
    mono: "\"IBM Plex Mono\"",
    glyphSmall: "20px",
    displayRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.25 },
    semiBold: { weight: 600, italic: false },
    tracking: "1.1px",
    shadowEdgeUp: "0px -1px 4px 0px rgba(0, 0, 0, 0.12)",
    spaceMicro: "2px",
    bodySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.5 },
    titleRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.2727 },
    bodySmallLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.7143 },
    shadowLift: "0px 4px 8px 0px rgba(0, 0, 0, 0.12)",
    scrim: "#000000",
    controlEdge: 3,
    glyph: "24px",
    wordState: 3,
    stroke: "1px",
    text: 4.5,
    heroSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "96px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    glyphHuge: "48px",
    labelTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.3333 },
    labelLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 2 },
    bodySmallSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.4286 },
    titleSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2727 },
    posterSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "64px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    veil: 0.35,
    bodyMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.5 },
    labelLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 2 },
    headlineRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    iconLayer: 3,
    family: "\"IBM Plex Sans\"",
    bodyRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.5 },
    headlineSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    radius: {
      _12: "12px",
      full: "999px",
      _4: "4px",
    },
    displayLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "40px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2 },
    spaceMedium: "12px",
    spaceBig: "20px",
    giantSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "200px", fontWeight: { weight: 600, italic: false }, lineHeight: 1 },
    highlight: 1.5,
    labelRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    titleMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.2727 },
    glyphBig: "32px",
    strokeBold: "4px",
    labelSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    bodySmallMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.4286 },
    connector: 0.55,
    headlineMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    ghost: 0.18,
    radiusRound: "999px",
    spaceSuperBig: "40px",
    medium: { weight: 500, italic: false },
    labelMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    link: {
      colour: "#00695c",
    },
    library: {
      color: {
        link: "#9a650f",
      },
    },
  },
  "Scheme=SIGNAL dark": {
    surfaceVariant: "#17222c",
    onBandMuted: "#6f8494",
    wordExtra: "#ff8a7a",
    wordMissed: "#80868d",
    bandVariant: "#101820",
    onAccent: "#06231f",
    error: "#ff8a7a",
    outline: "#536876",
    band: "#17222c",
    wordMatched: "#5bc98c",
    surface: "#101820",
    textSecondary: "#95a7b4",
    wordPartial: "#f2c56b",
    accent: "#4fd8c0",
    textPrimary: "#e6eef5",
    background: "#0a0f14",
    onBand: "#e6eef5",
    bandOutline: "#39505f",
    outlineVariant: "#39505f",
    page: "1120px",
    gap: "24px",
    corner: "12px",
    shadow: "0px 1px 2px 0px rgba(20, 23, 26, 0.05), 0px 12px 24px 0px rgba(20, 23, 26, 0.12)",
    measure: 66,
    type: {
      _96: "96px",
      _200: "200px",
      _18: "18px",
      _24: "24px",
      _22: "22px",
      _14: "14px",
      _12: "12px",
      _16: "16px",
      _32: "32px",
      _64: "64px",
      _40: "40px",
    },
    bodySmallRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.4286 },
    space: {
      _9: "9px",
      _11: "11px",
      _40: "40px",
      _4: "4px",
      _5: "5px",
      _20: "20px",
      _15: "15px",
      _8: "8px",
      _13: "13px",
      _2: "2px",
      _12: "12px",
    },
    bodySmallLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.7143 },
    size: {
      _72: "72px",
      _4: "4px",
      _150: "150px",
      _45: "45px",
      _20: "20px",
      _56: "56px",
      _48: "48px",
      _600: "600px",
      _12: "12px",
      _110: "110px",
      _64: "64px",
      _88: "88px",
      _70: "70px",
      _6: "6px",
      _60: "60px",
      _8: "8px",
      _160: "160px",
      _96: "96px",
      _80: "80px",
      _27: "27px",
      _42: "42px",
      _40: "40px",
      _16: "16px",
      _32: "32px",
      _200: "200px",
      _2: "2px",
      _340: "340px",
      _1: "1px",
      _24: "24px",
      _34: "34px",
      _28: "28px",
    },
    displayMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.25 },
    bodySmallTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.4286 },
    bodyLargeMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    bodyLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    displaySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.25 },
    bodyLargeRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "18px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    regular: { weight: 400, italic: false },
    share: {
      _100: 1,
      _75: 0.75,
      _66: 0.66,
      _25: 0.25,
      _33: 0.33,
      _50: 0.5,
    },
    strokeWide: "2px",
    spaceTiny: "4px",
    spaceSmall: "8px",
    mono: "\"IBM Plex Mono\"",
    glyphSmall: "20px",
    displayRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "32px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.25 },
    semiBold: { weight: 600, italic: false },
    tracking: "1.1px",
    shadowEdgeUp: "0px -1px 4px 0px rgba(0, 0, 0, 0.12)",
    spaceMicro: "2px",
    bodySemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.5 },
    titleRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.2727 },
    bodySmallLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.7143 },
    shadowLift: "0px 4px 8px 0px rgba(0, 0, 0, 0.12)",
    scrim: "#000000",
    controlEdge: 3,
    glyph: "24px",
    wordState: 3,
    stroke: "1px",
    text: 4.5,
    heroSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "96px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    glyphHuge: "48px",
    labelTrackedRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, letterSpacing: "1.1px", lineHeight: 1.3333 },
    labelLooseSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 2 },
    bodySmallSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.4286 },
    titleSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2727 },
    posterSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "64px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.1 },
    veil: 0.35,
    bodyMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.5 },
    labelLooseRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 2 },
    headlineRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    iconLayer: 3,
    family: "\"IBM Plex Sans\"",
    bodyRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "16px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.5 },
    headlineSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    radius: {
      _12: "12px",
      full: "999px",
      _4: "4px",
    },
    displayLargeSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "40px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.2 },
    spaceMedium: "12px",
    spaceBig: "20px",
    giantSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "200px", fontWeight: { weight: 600, italic: false }, lineHeight: 1 },
    highlight: 1.5,
    labelRegular: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 400, italic: false }, lineHeight: 1.3333 },
    titleMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "22px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.2727 },
    glyphBig: "32px",
    strokeBold: "4px",
    labelSemiBold: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 600, italic: false }, lineHeight: 1.3333 },
    bodySmallMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "14px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.4286 },
    connector: 0.55,
    headlineMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "24px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    ghost: 0.18,
    radiusRound: "999px",
    spaceSuperBig: "40px",
    medium: { weight: 500, italic: false },
    labelMedium: { fontFamily: "\"IBM Plex Sans\"", fontSize: "12px", fontWeight: { weight: 500, italic: false }, lineHeight: 1.3333 },
    link: {
      colour: "#4fd8c0",
    },
    library: {
      color: {
        link: "#9a650f",
      },
    },
  },
} as const;
export const defaultTheme = "Scheme=STUDIO_MONITOR light";
export type ThemeId = keyof typeof themes;
export type Tokens = (typeof themes)[ThemeId];
