(ns penpot.mcp.design.expr.sources
  (:require
   [clojure.string :as str]))

(def ^:private js-sources
  (update-vals
   {:js/random ["function random(a) {"
                "  return Math.random() * (a || 1);"
                "}"]
    :js/factorial ["function factorial(a) { // a!"
                   "  return gamma(a + 1);"
                   "}"]
    :js/min ["function min(array) {"
             "  if (arguments.length === 1 && Array.isArray(array)) {"
             "    return Math.min.apply(Math, array);"
             "  } else {"
             "    return Math.min.apply(Math, arguments);"
             "  }"
             "}"]
    :js/max ["function max(array) {"
             "  if (arguments.length === 1 && Array.isArray(array)) {"
             "    return Math.max.apply(Math, array);"
             "  } else {"
             "    return Math.max.apply(Math, arguments);"
             "  }"
             "}"]
    :js/condition ["function condition(cond, yep, nope) {"
                   "  return cond ? yep : nope;"
                   "}"]
    :js/gamma ["function gamma(n) {"
               "  var t, x;"
               ""
               "  if (isInteger(n)) {"
               "    if (n <= 0) {"
               "      return isFinite(n) ? Infinity : NaN;"
               "    }"
               ""
               "    if (n > 171) {"
               "      return Infinity; // Will overflow"
               "    }"
               ""
               "    var value = n - 2;"
               "    var res = n - 1;"
               "    while (value > 1) {"
               "      res *= value;"
               "      value--;"
               "    }"
               ""
               "    if (res === 0) {"
               "      res = 1; // 0! is per definition 1"
               "    }"
               ""
               "    return res;"
               "  }"
               ""
               "  if (n < 0.5) {"
               "    return Math.PI / (Math.sin(Math.PI * n) * gamma(1 - n));"
               "  }"
               ""
               "  if (n >= 171.35) {"
               "    return Infinity; // will overflow"
               "  }"
               ""
               "  if (n > 85.0) { // Extended Stirling Approx"
               "    var twoN = n * n;"
               "    var threeN = twoN * n;"
               "    var fourN = threeN * n;"
               "    var fiveN = fourN * n;"
               "    return Math.sqrt(2 * Math.PI / n) * Math.pow((n / Math.E), n) *"
               "      (1 + (1 / (12 * n)) + (1 / (288 * twoN)) - (139 / (51840 * threeN)) -"
               "      (571 / (2488320 * fourN)) + (163879 / (209018880 * fiveN)) +"
               "      (5246819 / (75246796800 * fiveN * n)));"
               "  }"
               ""
               "  --n;"
               "  x = GAMMA_P[0];"
               "  for (var i = 1; i < GAMMA_P.length; ++i) {"
               "    x += GAMMA_P[i] / (n + i);"
               "  }"
               ""
               "  t = n + GAMMA_G + 0.5;"
               "  return Math.sqrt(2 * Math.PI) * Math.pow(t, n + 0.5) * Math.exp(-t) * x;"
               "}"]
    :js/round-to ["function roundTo(value, exp) {"
                  "  // If the exp is undefined or zero..."
                  "  if (typeof exp === 'undefined' || +exp === 0) {"
                  "    return Math.round(value);"
                  "  }"
                  "  value = +value;"
                  "  exp = -(+exp);"
                  "  // If the value is not a number or the exp is not an integer..."
                  "  if (isNaN(value) || !(typeof exp === 'number' && exp % 1 === 0)) {"
                  "    return NaN;"
                  "  }"
                  "  // Shift"
                  "  value = value.toString().split('e');"
                  "  value = Math.round(+(value[0] + 'e' + (value[1] ? (+value[1] - exp) : -exp)));"
                  "  // Shift back"
                  "  value = value.toString().split('e');"
                  "  return +(value[0] + 'e' + (value[1] ? (+value[1] + exp) : exp));"
                  "}"]
    :js/map ["function arrayMap(f, a) {"
             "  if (typeof f !== 'function') {"
             "    throw new Error('First argument to map is not a function');"
             "  }"
             "  if (!Array.isArray(a)) {"
             "    throw new Error('Second argument to map is not an array');"
             "  }"
             "  return a.map(function (x, i) {"
             "    return f(x, i);"
             "  });"
             "}"]
    :js/fold ["function arrayFold(f, init, a) {"
              "  if (typeof f !== 'function') {"
              "    throw new Error('First argument to fold is not a function');"
              "  }"
              "  if (!Array.isArray(a)) {"
              "    throw new Error('Second argument to fold is not an array');"
              "  }"
              "  return a.reduce(function (acc, x, i) {"
              "    return f(acc, x, i);"
              "  }, init);"
              "}"]
    :js/filter ["function arrayFilter(f, a) {"
                "  if (typeof f !== 'function') {"
                "    throw new Error('First argument to filter is not a function');"
                "  }"
                "  if (!Array.isArray(a)) {"
                "    throw new Error('Second argument to filter is not an array');"
                "  }"
                "  return a.filter(function (x, i) {"
                "    return f(x, i);"
                "  });"
                "}"]
    :js/index-of ["function stringOrArrayIndexOf(target, s) {"
                  "  if (!(Array.isArray(s) || typeof s === 'string')) {"
                  "    throw new Error('Second argument to indexOf is not a string or array');"
                  "  }"
                  ""
                  "  return s.indexOf(target);"
                  "}"]
    :js/join ["function arrayJoin(sep, a) {"
              "  if (!Array.isArray(a)) {"
              "    throw new Error('Second argument to join is not an array');"
              "  }"
              ""
              "  return a.join(sep);"
              "}"]
    :js/sum ["function sum(array) {"
             "  if (!Array.isArray(array)) {"
             "    throw new Error('Sum argument is not an array');"
             "  }"
             ""
             "  return array.reduce(function (total, value) {"
             "    return total + Number(value);"
             "  }, 0);"
             "}"]
    :js/neg ["function neg(a) {"
             "  return -a;"
             "}"]
    :js/not ["function not(a) {"
             "  return !a;"
             "}"]
    :js/length ["function stringOrArrayLength(s) {"
                "  if (Array.isArray(s)) {"
                "    return s.length;"
                "  }"
                "  return String(s).length;"
                "}"]
    :lambda ["function () {"
             "          var scope = Object.assign({}, values);"
             "          for (var i = 0, len = args.length; i < len; i++) {"
             "            scope[args[i]] = arguments[i];"
             "          }"
             "          return evaluate(n2, expr, scope);"
             "        }"]}
   #(str/join "\n" %)))

(defn native-source [f]
  (let [id (:id f)]
    (or (get js-sources (if (or (keyword? id) (vector? id)) id :lambda))
        (str "function " (:name f) "() { [native code] }"))))
