services:
  penpot-mcp:
    image: ghcr.io/pdasilem/penpot-mcp-server-unofficial:2.18.1.5
    restart: unless-stopped
    depends_on:
      - penpot-frontend
    networks:
      - penpot
    env_file: ./penpot-mcp-server-unofficial/.env
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    mem_limit: 512m
    pids_limit: 256
