package com.recorded.design

data class FontWeightToken(val weight: Int, val italic: Boolean)

data class TypographyToken(
    val fontFamily: List<String>?,
    val fontSize: Float?,
    val fontWeight: FontWeightToken?,
    val lineHeight: Float?,
    val letterSpacing: Float?,
    val textCase: String?,
    val textDecoration: String?,
)

data class ShadowToken(
    val offsetX: Float,
    val offsetY: Float,
    val blur: Float,
    val spread: Float,
    val color: Long,
    val inset: Boolean,
)

data class Tokens(
    val surfaceVariant: Long,
    val onBandMuted: Long,
    val wordExtra: Long,
    val wordMissed: Long,
    val bandVariant: Long,
    val onAccent: Long,
    val error: Long,
    val outline: Long,
    val band: Long,
    val wordMatched: Long,
    val surface: Long,
    val textSecondary: Long,
    val wordPartial: Long,
    val accent: Long,
    val textPrimary: Long,
    val background: Long,
    val onBand: Long,
    val bandOutline: Long,
    val outlineVariant: Long,
    val page: Float,
    val gap: Float,
    val corner: Float,
    val shadow: List<ShadowToken>,
    val measure: Float,
    val type: TokensType,
    val bodySmallRegular: TypographyToken,
    val space: TokensSpace,
    val bodySmallLooseRegular: TypographyToken,
    val size: TokensSize,
    val displayMedium: TypographyToken,
    val bodySmallTrackedRegular: TypographyToken,
    val bodyLargeMedium: TypographyToken,
    val bodyLargeSemiBold: TypographyToken,
    val displaySemiBold: TypographyToken,
    val bodyLargeRegular: TypographyToken,
    val regular: FontWeightToken,
    val share: TokensShare,
    val strokeWide: Float,
    val spaceTiny: Float,
    val spaceSmall: Float,
    val mono: List<String>,
    val glyphSmall: Float,
    val displayRegular: TypographyToken,
    val semiBold: FontWeightToken,
    val tracking: Float,
    val shadowEdgeUp: List<ShadowToken>,
    val spaceMicro: Float,
    val bodySemiBold: TypographyToken,
    val titleRegular: TypographyToken,
    val bodySmallLooseSemiBold: TypographyToken,
    val shadowLift: List<ShadowToken>,
    val scrim: Long,
    val controlEdge: Float,
    val glyph: Float,
    val wordState: Float,
    val stroke: Float,
    val text: Float,
    val heroSemiBold: TypographyToken,
    val glyphHuge: Float,
    val labelTrackedRegular: TypographyToken,
    val labelLooseSemiBold: TypographyToken,
    val bodySmallSemiBold: TypographyToken,
    val titleSemiBold: TypographyToken,
    val posterSemiBold: TypographyToken,
    val veil: Float,
    val bodyMedium: TypographyToken,
    val labelLooseRegular: TypographyToken,
    val headlineRegular: TypographyToken,
    val iconLayer: Float,
    val family: List<String>,
    val bodyRegular: TypographyToken,
    val headlineSemiBold: TypographyToken,
    val radius: TokensRadius,
    val displayLargeSemiBold: TypographyToken,
    val spaceMedium: Float,
    val spaceBig: Float,
    val giantSemiBold: TypographyToken,
    val highlight: Float,
    val labelRegular: TypographyToken,
    val titleMedium: TypographyToken,
    val glyphBig: Float,
    val strokeBold: Float,
    val labelSemiBold: TypographyToken,
    val bodySmallMedium: TypographyToken,
    val connector: Float,
    val headlineMedium: TypographyToken,
    val ghost: Float,
    val radiusRound: Float,
    val spaceSuperBig: Float,
    val medium: FontWeightToken,
    val labelMedium: TypographyToken,
    val link: TokensLink,
    val library: TokensLibrary,
)

data class TokensType(
    val _96: Float,
    val _200: Float,
    val _18: Float,
    val _24: Float,
    val _22: Float,
    val _14: Float,
    val _12: Float,
    val _16: Float,
    val _32: Float,
    val _64: Float,
    val _40: Float,
)

data class TokensSpace(
    val _9: Float,
    val _11: Float,
    val _40: Float,
    val _4: Float,
    val _5: Float,
    val _20: Float,
    val _15: Float,
    val _8: Float,
    val _13: Float,
    val _2: Float,
    val _12: Float,
)

data class TokensSize(
    val _72: Float,
    val _4: Float,
    val _150: Float,
    val _45: Float,
    val _20: Float,
    val _56: Float,
    val _48: Float,
    val _600: Float,
    val _12: Float,
    val _110: Float,
    val _64: Float,
    val _88: Float,
    val _70: Float,
    val _6: Float,
    val _60: Float,
    val _8: Float,
    val _160: Float,
    val _96: Float,
    val _80: Float,
    val _27: Float,
    val _42: Float,
    val _40: Float,
    val _16: Float,
    val _32: Float,
    val _200: Float,
    val _2: Float,
    val _340: Float,
    val _1: Float,
    val _24: Float,
    val _34: Float,
    val _28: Float,
)

data class TokensShare(
    val _100: Float,
    val _75: Float,
    val _66: Float,
    val _25: Float,
    val _33: Float,
    val _50: Float,
)

data class TokensRadius(
    val _12: Float,
    val full: Float,
    val _4: Float,
)

data class TokensLink(
    val colour: Long,
)

data class TokensLibrary(
    val colorLink: Long,
)

object TokensThemes {
    val schemeStudioMonitorLight: Tokens = Tokens(
        surfaceVariant = 0xFFE4E7EA,
        onBandMuted = 0xFF7D858A,
        wordExtra = 0xFFEA0010,
        wordMissed = 0xFF737373,
        bandVariant = 0xFF191C1F,
        onAccent = 0xFFFFFFFF,
        error = 0xFFA33A26,
        outline = 0xFF8A8E91,
        band = 0xFF0E1012,
        wordMatched = 0xFF00863C,
        surface = 0xFFFFFFFF,
        textSecondary = 0xFF6B7276,
        wordPartial = 0xFF9E6A00,
        accent = 0xFF9A650F,
        textPrimary = 0xFF1A1D20,
        background = 0xFFF4F5F6,
        onBand = 0xFFE8EAEC,
        bandOutline = 0xFF4A5054,
        outlineVariant = 0xFFC9CDD0,
        page = 1120.0f,
        gap = 24.0f,
        corner = 12.0f,
        shadow = listOf(ShadowToken(offsetX = 0.0f, offsetY = 1.0f, blur = 2.0f, spread = 0.0f, color = 0x0D14171AL, inset = false), ShadowToken(offsetX = 0.0f, offsetY = 12.0f, blur = 24.0f, spread = 0.0f, color = 0x1F14171AL, inset = false)),
        measure = 66.0f,
        type = TokensType(
            _96 = 96.0f,
            _200 = 200.0f,
            _18 = 18.0f,
            _24 = 24.0f,
            _22 = 22.0f,
            _14 = 14.0f,
            _12 = 12.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _64 = 64.0f,
            _40 = 40.0f,
        ),
        bodySmallRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        space = TokensSpace(
            _9 = 9.0f,
            _11 = 11.0f,
            _40 = 40.0f,
            _4 = 4.0f,
            _5 = 5.0f,
            _20 = 20.0f,
            _15 = 15.0f,
            _8 = 8.0f,
            _13 = 13.0f,
            _2 = 2.0f,
            _12 = 12.0f,
        ),
        bodySmallLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        size = TokensSize(
            _72 = 72.0f,
            _4 = 4.0f,
            _150 = 150.0f,
            _45 = 45.0f,
            _20 = 20.0f,
            _56 = 56.0f,
            _48 = 48.0f,
            _600 = 600.0f,
            _12 = 12.0f,
            _110 = 110.0f,
            _64 = 64.0f,
            _88 = 88.0f,
            _70 = 70.0f,
            _6 = 6.0f,
            _60 = 60.0f,
            _8 = 8.0f,
            _160 = 160.0f,
            _96 = 96.0f,
            _80 = 80.0f,
            _27 = 27.0f,
            _42 = 42.0f,
            _40 = 40.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _200 = 200.0f,
            _2 = 2.0f,
            _340 = 340.0f,
            _1 = 1.0f,
            _24 = 24.0f,
            _34 = 34.0f,
            _28 = 28.0f,
        ),
        displayMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        bodyLargeMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        displaySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        regular = FontWeightToken(weight = 400, italic = false),
        share = TokensShare(
            _100 = 1.0f,
            _75 = 0.75f,
            _66 = 0.66f,
            _25 = 0.25f,
            _33 = 0.33f,
            _50 = 0.5f,
        ),
        strokeWide = 2.0f,
        spaceTiny = 4.0f,
        spaceSmall = 8.0f,
        mono = listOf("IBM Plex Mono"),
        glyphSmall = 20.0f,
        displayRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        semiBold = FontWeightToken(weight = 600, italic = false),
        tracking = 1.1f,
        shadowEdgeUp = listOf(ShadowToken(offsetX = 0.0f, offsetY = -1.0f, blur = 4.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        spaceMicro = 2.0f,
        bodySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        titleRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        shadowLift = listOf(ShadowToken(offsetX = 0.0f, offsetY = 4.0f, blur = 8.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        scrim = 0xFF000000,
        controlEdge = 3.0f,
        glyph = 24.0f,
        wordState = 3.0f,
        stroke = 1.0f,
        text = 4.5f,
        heroSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 96.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphHuge = 48.0f,
        labelTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        labelLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        titleSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        posterSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 64.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        veil = 0.35f,
        bodyMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        labelLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        iconLayer = 3.0f,
        family = listOf("IBM Plex Sans"),
        bodyRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        radius = TokensRadius(
            _12 = 12.0f,
            full = 999.0f,
            _4 = 4.0f,
        ),
        displayLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 40.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2f, letterSpacing = null, textCase = null, textDecoration = null),
        spaceMedium = 12.0f,
        spaceBig = 20.0f,
        giantSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 200.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.0f, letterSpacing = null, textCase = null, textDecoration = null),
        highlight = 1.5f,
        labelRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        titleMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphBig = 32.0f,
        strokeBold = 4.0f,
        labelSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        connector = 0.55f,
        headlineMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        ghost = 0.18f,
        radiusRound = 999.0f,
        spaceSuperBig = 40.0f,
        medium = FontWeightToken(weight = 500, italic = false),
        labelMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        link = TokensLink(
            colour = 0xFF9A650F,
        ),
        library = TokensLibrary(
            colorLink = 0xFF9A650F,
        ),
    )

    val schemeStudioMonitorDark: Tokens = Tokens(
        surfaceVariant = 0xFF22262A,
        onBandMuted = 0xFF7D858A,
        wordExtra = 0xFFEA0010,
        wordMissed = 0xFF737373,
        bandVariant = 0xFF191C1F,
        onAccent = 0xFF14171A,
        error = 0xFFE3705B,
        outline = 0xFF63696C,
        band = 0xFF22262A,
        wordMatched = 0xFF00863C,
        surface = 0xFF191C1F,
        textSecondary = 0xFFA0A7AD,
        wordPartial = 0xFF9E6A00,
        accent = 0xFFF2A93B,
        textPrimary = 0xFFE8EAEC,
        background = 0xFF0E1012,
        onBand = 0xFFE8EAEC,
        bandOutline = 0xFF4A5054,
        outlineVariant = 0xFF4A5054,
        page = 1120.0f,
        gap = 24.0f,
        corner = 12.0f,
        shadow = listOf(ShadowToken(offsetX = 0.0f, offsetY = 1.0f, blur = 2.0f, spread = 0.0f, color = 0x0D14171AL, inset = false), ShadowToken(offsetX = 0.0f, offsetY = 12.0f, blur = 24.0f, spread = 0.0f, color = 0x1F14171AL, inset = false)),
        measure = 66.0f,
        type = TokensType(
            _96 = 96.0f,
            _200 = 200.0f,
            _18 = 18.0f,
            _24 = 24.0f,
            _22 = 22.0f,
            _14 = 14.0f,
            _12 = 12.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _64 = 64.0f,
            _40 = 40.0f,
        ),
        bodySmallRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        space = TokensSpace(
            _9 = 9.0f,
            _11 = 11.0f,
            _40 = 40.0f,
            _4 = 4.0f,
            _5 = 5.0f,
            _20 = 20.0f,
            _15 = 15.0f,
            _8 = 8.0f,
            _13 = 13.0f,
            _2 = 2.0f,
            _12 = 12.0f,
        ),
        bodySmallLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        size = TokensSize(
            _72 = 72.0f,
            _4 = 4.0f,
            _150 = 150.0f,
            _45 = 45.0f,
            _20 = 20.0f,
            _56 = 56.0f,
            _48 = 48.0f,
            _600 = 600.0f,
            _12 = 12.0f,
            _110 = 110.0f,
            _64 = 64.0f,
            _88 = 88.0f,
            _70 = 70.0f,
            _6 = 6.0f,
            _60 = 60.0f,
            _8 = 8.0f,
            _160 = 160.0f,
            _96 = 96.0f,
            _80 = 80.0f,
            _27 = 27.0f,
            _42 = 42.0f,
            _40 = 40.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _200 = 200.0f,
            _2 = 2.0f,
            _340 = 340.0f,
            _1 = 1.0f,
            _24 = 24.0f,
            _34 = 34.0f,
            _28 = 28.0f,
        ),
        displayMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        bodyLargeMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        displaySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        regular = FontWeightToken(weight = 400, italic = false),
        share = TokensShare(
            _100 = 1.0f,
            _75 = 0.75f,
            _66 = 0.66f,
            _25 = 0.25f,
            _33 = 0.33f,
            _50 = 0.5f,
        ),
        strokeWide = 2.0f,
        spaceTiny = 4.0f,
        spaceSmall = 8.0f,
        mono = listOf("IBM Plex Mono"),
        glyphSmall = 20.0f,
        displayRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        semiBold = FontWeightToken(weight = 600, italic = false),
        tracking = 1.1f,
        shadowEdgeUp = listOf(ShadowToken(offsetX = 0.0f, offsetY = -1.0f, blur = 4.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        spaceMicro = 2.0f,
        bodySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        titleRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        shadowLift = listOf(ShadowToken(offsetX = 0.0f, offsetY = 4.0f, blur = 8.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        scrim = 0xFF000000,
        controlEdge = 3.0f,
        glyph = 24.0f,
        wordState = 3.0f,
        stroke = 1.0f,
        text = 4.5f,
        heroSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 96.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphHuge = 48.0f,
        labelTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        labelLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        titleSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        posterSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 64.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        veil = 0.35f,
        bodyMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        labelLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        iconLayer = 3.0f,
        family = listOf("IBM Plex Sans"),
        bodyRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        radius = TokensRadius(
            _12 = 12.0f,
            full = 999.0f,
            _4 = 4.0f,
        ),
        displayLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 40.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2f, letterSpacing = null, textCase = null, textDecoration = null),
        spaceMedium = 12.0f,
        spaceBig = 20.0f,
        giantSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 200.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.0f, letterSpacing = null, textCase = null, textDecoration = null),
        highlight = 1.5f,
        labelRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        titleMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphBig = 32.0f,
        strokeBold = 4.0f,
        labelSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        connector = 0.55f,
        headlineMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        ghost = 0.18f,
        radiusRound = 999.0f,
        spaceSuperBig = 40.0f,
        medium = FontWeightToken(weight = 500, italic = false),
        labelMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        link = TokensLink(
            colour = 0xFFF2A93B,
        ),
        library = TokensLibrary(
            colorLink = 0xFF9A650F,
        ),
    )

    val schemePaperAndInkLight: Tokens = Tokens(
        surfaceVariant = 0xFFEBE4D8,
        onBandMuted = 0xFF938576,
        wordExtra = 0xFFA6432B,
        wordMissed = 0xFF6F757C,
        bandVariant = 0xFF201B16,
        onAccent = 0xFFFFFDF9,
        error = 0xFFA6432B,
        outline = 0xFF938B7F,
        band = 0xFF17130F,
        wordMatched = 0xFF2F6B44,
        surface = 0xFFFFFDF9,
        textSecondary = 0xFF6B5F51,
        wordPartial = 0xFFB37619,
        accent = 0xFF2E4B7A,
        textPrimary = 0xFF221C16,
        background = 0xFFF7F3EC,
        onBand = 0xFFF3EBE1,
        bandOutline = 0xFF5A4E41,
        outlineVariant = 0xFFD6CCBC,
        page = 1120.0f,
        gap = 24.0f,
        corner = 12.0f,
        shadow = listOf(ShadowToken(offsetX = 0.0f, offsetY = 1.0f, blur = 2.0f, spread = 0.0f, color = 0x0D14171AL, inset = false), ShadowToken(offsetX = 0.0f, offsetY = 12.0f, blur = 24.0f, spread = 0.0f, color = 0x1F14171AL, inset = false)),
        measure = 66.0f,
        type = TokensType(
            _96 = 96.0f,
            _200 = 200.0f,
            _18 = 18.0f,
            _24 = 24.0f,
            _22 = 22.0f,
            _14 = 14.0f,
            _12 = 12.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _64 = 64.0f,
            _40 = 40.0f,
        ),
        bodySmallRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        space = TokensSpace(
            _9 = 9.0f,
            _11 = 11.0f,
            _40 = 40.0f,
            _4 = 4.0f,
            _5 = 5.0f,
            _20 = 20.0f,
            _15 = 15.0f,
            _8 = 8.0f,
            _13 = 13.0f,
            _2 = 2.0f,
            _12 = 12.0f,
        ),
        bodySmallLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        size = TokensSize(
            _72 = 72.0f,
            _4 = 4.0f,
            _150 = 150.0f,
            _45 = 45.0f,
            _20 = 20.0f,
            _56 = 56.0f,
            _48 = 48.0f,
            _600 = 600.0f,
            _12 = 12.0f,
            _110 = 110.0f,
            _64 = 64.0f,
            _88 = 88.0f,
            _70 = 70.0f,
            _6 = 6.0f,
            _60 = 60.0f,
            _8 = 8.0f,
            _160 = 160.0f,
            _96 = 96.0f,
            _80 = 80.0f,
            _27 = 27.0f,
            _42 = 42.0f,
            _40 = 40.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _200 = 200.0f,
            _2 = 2.0f,
            _340 = 340.0f,
            _1 = 1.0f,
            _24 = 24.0f,
            _34 = 34.0f,
            _28 = 28.0f,
        ),
        displayMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        bodyLargeMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        displaySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        regular = FontWeightToken(weight = 400, italic = false),
        share = TokensShare(
            _100 = 1.0f,
            _75 = 0.75f,
            _66 = 0.66f,
            _25 = 0.25f,
            _33 = 0.33f,
            _50 = 0.5f,
        ),
        strokeWide = 2.0f,
        spaceTiny = 4.0f,
        spaceSmall = 8.0f,
        mono = listOf("IBM Plex Mono"),
        glyphSmall = 20.0f,
        displayRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        semiBold = FontWeightToken(weight = 600, italic = false),
        tracking = 1.1f,
        shadowEdgeUp = listOf(ShadowToken(offsetX = 0.0f, offsetY = -1.0f, blur = 4.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        spaceMicro = 2.0f,
        bodySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        titleRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        shadowLift = listOf(ShadowToken(offsetX = 0.0f, offsetY = 4.0f, blur = 8.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        scrim = 0xFF000000,
        controlEdge = 3.0f,
        glyph = 24.0f,
        wordState = 3.0f,
        stroke = 1.0f,
        text = 4.5f,
        heroSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 96.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphHuge = 48.0f,
        labelTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        labelLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        titleSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        posterSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 64.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        veil = 0.35f,
        bodyMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        labelLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        iconLayer = 3.0f,
        family = listOf("IBM Plex Sans"),
        bodyRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        radius = TokensRadius(
            _12 = 12.0f,
            full = 999.0f,
            _4 = 4.0f,
        ),
        displayLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 40.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2f, letterSpacing = null, textCase = null, textDecoration = null),
        spaceMedium = 12.0f,
        spaceBig = 20.0f,
        giantSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 200.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.0f, letterSpacing = null, textCase = null, textDecoration = null),
        highlight = 1.5f,
        labelRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        titleMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphBig = 32.0f,
        strokeBold = 4.0f,
        labelSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        connector = 0.55f,
        headlineMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        ghost = 0.18f,
        radiusRound = 999.0f,
        spaceSuperBig = 40.0f,
        medium = FontWeightToken(weight = 500, italic = false),
        labelMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        link = TokensLink(
            colour = 0xFF2E4B7A,
        ),
        library = TokensLibrary(
            colorLink = 0xFF9A650F,
        ),
    )

    val schemePaperAndInkDark: Tokens = Tokens(
        surfaceVariant = 0xFF2C251E,
        onBandMuted = 0xFF938576,
        wordExtra = 0xFFE08E76,
        wordMissed = 0xFF80868D,
        bandVariant = 0xFF201B16,
        onAccent = 0xFF161B24,
        error = 0xFFE08E76,
        outline = 0xFF716659,
        band = 0xFF2C251E,
        wordMatched = 0xFF7FC79A,
        surface = 0xFF201B16,
        textSecondary = 0xFFB9AC9C,
        wordPartial = 0xFFF2A93B,
        accent = 0xFF9FBEE8,
        textPrimary = 0xFFF3EBE1,
        background = 0xFF17130F,
        onBand = 0xFFF3EBE1,
        bandOutline = 0xFF5A4E41,
        outlineVariant = 0xFF5A4E41,
        page = 1120.0f,
        gap = 24.0f,
        corner = 12.0f,
        shadow = listOf(ShadowToken(offsetX = 0.0f, offsetY = 1.0f, blur = 2.0f, spread = 0.0f, color = 0x0D14171AL, inset = false), ShadowToken(offsetX = 0.0f, offsetY = 12.0f, blur = 24.0f, spread = 0.0f, color = 0x1F14171AL, inset = false)),
        measure = 66.0f,
        type = TokensType(
            _96 = 96.0f,
            _200 = 200.0f,
            _18 = 18.0f,
            _24 = 24.0f,
            _22 = 22.0f,
            _14 = 14.0f,
            _12 = 12.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _64 = 64.0f,
            _40 = 40.0f,
        ),
        bodySmallRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        space = TokensSpace(
            _9 = 9.0f,
            _11 = 11.0f,
            _40 = 40.0f,
            _4 = 4.0f,
            _5 = 5.0f,
            _20 = 20.0f,
            _15 = 15.0f,
            _8 = 8.0f,
            _13 = 13.0f,
            _2 = 2.0f,
            _12 = 12.0f,
        ),
        bodySmallLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        size = TokensSize(
            _72 = 72.0f,
            _4 = 4.0f,
            _150 = 150.0f,
            _45 = 45.0f,
            _20 = 20.0f,
            _56 = 56.0f,
            _48 = 48.0f,
            _600 = 600.0f,
            _12 = 12.0f,
            _110 = 110.0f,
            _64 = 64.0f,
            _88 = 88.0f,
            _70 = 70.0f,
            _6 = 6.0f,
            _60 = 60.0f,
            _8 = 8.0f,
            _160 = 160.0f,
            _96 = 96.0f,
            _80 = 80.0f,
            _27 = 27.0f,
            _42 = 42.0f,
            _40 = 40.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _200 = 200.0f,
            _2 = 2.0f,
            _340 = 340.0f,
            _1 = 1.0f,
            _24 = 24.0f,
            _34 = 34.0f,
            _28 = 28.0f,
        ),
        displayMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        bodyLargeMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        displaySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        regular = FontWeightToken(weight = 400, italic = false),
        share = TokensShare(
            _100 = 1.0f,
            _75 = 0.75f,
            _66 = 0.66f,
            _25 = 0.25f,
            _33 = 0.33f,
            _50 = 0.5f,
        ),
        strokeWide = 2.0f,
        spaceTiny = 4.0f,
        spaceSmall = 8.0f,
        mono = listOf("IBM Plex Mono"),
        glyphSmall = 20.0f,
        displayRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        semiBold = FontWeightToken(weight = 600, italic = false),
        tracking = 1.1f,
        shadowEdgeUp = listOf(ShadowToken(offsetX = 0.0f, offsetY = -1.0f, blur = 4.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        spaceMicro = 2.0f,
        bodySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        titleRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        shadowLift = listOf(ShadowToken(offsetX = 0.0f, offsetY = 4.0f, blur = 8.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        scrim = 0xFF000000,
        controlEdge = 3.0f,
        glyph = 24.0f,
        wordState = 3.0f,
        stroke = 1.0f,
        text = 4.5f,
        heroSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 96.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphHuge = 48.0f,
        labelTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        labelLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        titleSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        posterSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 64.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        veil = 0.35f,
        bodyMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        labelLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        iconLayer = 3.0f,
        family = listOf("IBM Plex Sans"),
        bodyRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        radius = TokensRadius(
            _12 = 12.0f,
            full = 999.0f,
            _4 = 4.0f,
        ),
        displayLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 40.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2f, letterSpacing = null, textCase = null, textDecoration = null),
        spaceMedium = 12.0f,
        spaceBig = 20.0f,
        giantSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 200.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.0f, letterSpacing = null, textCase = null, textDecoration = null),
        highlight = 1.5f,
        labelRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        titleMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphBig = 32.0f,
        strokeBold = 4.0f,
        labelSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        connector = 0.55f,
        headlineMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        ghost = 0.18f,
        radiusRound = 999.0f,
        spaceSuperBig = 40.0f,
        medium = FontWeightToken(weight = 500, italic = false),
        labelMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        link = TokensLink(
            colour = 0xFF9FBEE8,
        ),
        library = TokensLibrary(
            colorLink = 0xFF9A650F,
        ),
    )

    val schemeSignalLight: Tokens = Tokens(
        surfaceVariant = 0xFFE2EAEF,
        onBandMuted = 0xFF6F8494,
        wordExtra = 0xFFB23A2B,
        wordMissed = 0xFF6F757C,
        bandVariant = 0xFF101820,
        onAccent = 0xFFFFFFFF,
        error = 0xFFB23A2B,
        outline = 0xFF7F909D,
        band = 0xFF0A0F14,
        wordMatched = 0xFF2F8F5B,
        surface = 0xFFFFFFFF,
        textSecondary = 0xFF4A5D6B,
        wordPartial = 0xFF8A5A00,
        accent = 0xFF00695C,
        textPrimary = 0xFF0A1219,
        background = 0xFFF2F6F8,
        onBand = 0xFFE6EEF5,
        bandOutline = 0xFF39505F,
        outlineVariant = 0xFFA8BCCB,
        page = 1120.0f,
        gap = 24.0f,
        corner = 12.0f,
        shadow = listOf(ShadowToken(offsetX = 0.0f, offsetY = 1.0f, blur = 2.0f, spread = 0.0f, color = 0x0D14171AL, inset = false), ShadowToken(offsetX = 0.0f, offsetY = 12.0f, blur = 24.0f, spread = 0.0f, color = 0x1F14171AL, inset = false)),
        measure = 66.0f,
        type = TokensType(
            _96 = 96.0f,
            _200 = 200.0f,
            _18 = 18.0f,
            _24 = 24.0f,
            _22 = 22.0f,
            _14 = 14.0f,
            _12 = 12.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _64 = 64.0f,
            _40 = 40.0f,
        ),
        bodySmallRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        space = TokensSpace(
            _9 = 9.0f,
            _11 = 11.0f,
            _40 = 40.0f,
            _4 = 4.0f,
            _5 = 5.0f,
            _20 = 20.0f,
            _15 = 15.0f,
            _8 = 8.0f,
            _13 = 13.0f,
            _2 = 2.0f,
            _12 = 12.0f,
        ),
        bodySmallLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        size = TokensSize(
            _72 = 72.0f,
            _4 = 4.0f,
            _150 = 150.0f,
            _45 = 45.0f,
            _20 = 20.0f,
            _56 = 56.0f,
            _48 = 48.0f,
            _600 = 600.0f,
            _12 = 12.0f,
            _110 = 110.0f,
            _64 = 64.0f,
            _88 = 88.0f,
            _70 = 70.0f,
            _6 = 6.0f,
            _60 = 60.0f,
            _8 = 8.0f,
            _160 = 160.0f,
            _96 = 96.0f,
            _80 = 80.0f,
            _27 = 27.0f,
            _42 = 42.0f,
            _40 = 40.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _200 = 200.0f,
            _2 = 2.0f,
            _340 = 340.0f,
            _1 = 1.0f,
            _24 = 24.0f,
            _34 = 34.0f,
            _28 = 28.0f,
        ),
        displayMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        bodyLargeMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        displaySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        regular = FontWeightToken(weight = 400, italic = false),
        share = TokensShare(
            _100 = 1.0f,
            _75 = 0.75f,
            _66 = 0.66f,
            _25 = 0.25f,
            _33 = 0.33f,
            _50 = 0.5f,
        ),
        strokeWide = 2.0f,
        spaceTiny = 4.0f,
        spaceSmall = 8.0f,
        mono = listOf("IBM Plex Mono"),
        glyphSmall = 20.0f,
        displayRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        semiBold = FontWeightToken(weight = 600, italic = false),
        tracking = 1.1f,
        shadowEdgeUp = listOf(ShadowToken(offsetX = 0.0f, offsetY = -1.0f, blur = 4.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        spaceMicro = 2.0f,
        bodySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        titleRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        shadowLift = listOf(ShadowToken(offsetX = 0.0f, offsetY = 4.0f, blur = 8.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        scrim = 0xFF000000,
        controlEdge = 3.0f,
        glyph = 24.0f,
        wordState = 3.0f,
        stroke = 1.0f,
        text = 4.5f,
        heroSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 96.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphHuge = 48.0f,
        labelTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        labelLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        titleSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        posterSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 64.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        veil = 0.35f,
        bodyMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        labelLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        iconLayer = 3.0f,
        family = listOf("IBM Plex Sans"),
        bodyRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        radius = TokensRadius(
            _12 = 12.0f,
            full = 999.0f,
            _4 = 4.0f,
        ),
        displayLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 40.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2f, letterSpacing = null, textCase = null, textDecoration = null),
        spaceMedium = 12.0f,
        spaceBig = 20.0f,
        giantSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 200.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.0f, letterSpacing = null, textCase = null, textDecoration = null),
        highlight = 1.5f,
        labelRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        titleMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphBig = 32.0f,
        strokeBold = 4.0f,
        labelSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        connector = 0.55f,
        headlineMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        ghost = 0.18f,
        radiusRound = 999.0f,
        spaceSuperBig = 40.0f,
        medium = FontWeightToken(weight = 500, italic = false),
        labelMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        link = TokensLink(
            colour = 0xFF00695C,
        ),
        library = TokensLibrary(
            colorLink = 0xFF9A650F,
        ),
    )

    val schemeSignalDark: Tokens = Tokens(
        surfaceVariant = 0xFF17222C,
        onBandMuted = 0xFF6F8494,
        wordExtra = 0xFFFF8A7A,
        wordMissed = 0xFF80868D,
        bandVariant = 0xFF101820,
        onAccent = 0xFF06231F,
        error = 0xFFFF8A7A,
        outline = 0xFF536876,
        band = 0xFF17222C,
        wordMatched = 0xFF5BC98C,
        surface = 0xFF101820,
        textSecondary = 0xFF95A7B4,
        wordPartial = 0xFFF2C56B,
        accent = 0xFF4FD8C0,
        textPrimary = 0xFFE6EEF5,
        background = 0xFF0A0F14,
        onBand = 0xFFE6EEF5,
        bandOutline = 0xFF39505F,
        outlineVariant = 0xFF39505F,
        page = 1120.0f,
        gap = 24.0f,
        corner = 12.0f,
        shadow = listOf(ShadowToken(offsetX = 0.0f, offsetY = 1.0f, blur = 2.0f, spread = 0.0f, color = 0x0D14171AL, inset = false), ShadowToken(offsetX = 0.0f, offsetY = 12.0f, blur = 24.0f, spread = 0.0f, color = 0x1F14171AL, inset = false)),
        measure = 66.0f,
        type = TokensType(
            _96 = 96.0f,
            _200 = 200.0f,
            _18 = 18.0f,
            _24 = 24.0f,
            _22 = 22.0f,
            _14 = 14.0f,
            _12 = 12.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _64 = 64.0f,
            _40 = 40.0f,
        ),
        bodySmallRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        space = TokensSpace(
            _9 = 9.0f,
            _11 = 11.0f,
            _40 = 40.0f,
            _4 = 4.0f,
            _5 = 5.0f,
            _20 = 20.0f,
            _15 = 15.0f,
            _8 = 8.0f,
            _13 = 13.0f,
            _2 = 2.0f,
            _12 = 12.0f,
        ),
        bodySmallLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        size = TokensSize(
            _72 = 72.0f,
            _4 = 4.0f,
            _150 = 150.0f,
            _45 = 45.0f,
            _20 = 20.0f,
            _56 = 56.0f,
            _48 = 48.0f,
            _600 = 600.0f,
            _12 = 12.0f,
            _110 = 110.0f,
            _64 = 64.0f,
            _88 = 88.0f,
            _70 = 70.0f,
            _6 = 6.0f,
            _60 = 60.0f,
            _8 = 8.0f,
            _160 = 160.0f,
            _96 = 96.0f,
            _80 = 80.0f,
            _27 = 27.0f,
            _42 = 42.0f,
            _40 = 40.0f,
            _16 = 16.0f,
            _32 = 32.0f,
            _200 = 200.0f,
            _2 = 2.0f,
            _340 = 340.0f,
            _1 = 1.0f,
            _24 = 24.0f,
            _34 = 34.0f,
            _28 = 28.0f,
        ),
        displayMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.4286f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        bodyLargeMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        displaySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        bodyLargeRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 18.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        regular = FontWeightToken(weight = 400, italic = false),
        share = TokensShare(
            _100 = 1.0f,
            _75 = 0.75f,
            _66 = 0.66f,
            _25 = 0.25f,
            _33 = 0.33f,
            _50 = 0.5f,
        ),
        strokeWide = 2.0f,
        spaceTiny = 4.0f,
        spaceSmall = 8.0f,
        mono = listOf("IBM Plex Mono"),
        glyphSmall = 20.0f,
        displayRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 32.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.25f, letterSpacing = null, textCase = null, textDecoration = null),
        semiBold = FontWeightToken(weight = 600, italic = false),
        tracking = 1.1f,
        shadowEdgeUp = listOf(ShadowToken(offsetX = 0.0f, offsetY = -1.0f, blur = 4.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        spaceMicro = 2.0f,
        bodySemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        titleRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.7143f, letterSpacing = null, textCase = null, textDecoration = null),
        shadowLift = listOf(ShadowToken(offsetX = 0.0f, offsetY = 4.0f, blur = 8.0f, spread = 0.0f, color = 0x1F000000L, inset = false)),
        scrim = 0xFF000000,
        controlEdge = 3.0f,
        glyph = 24.0f,
        wordState = 3.0f,
        stroke = 1.0f,
        text = 4.5f,
        heroSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 96.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphHuge = 48.0f,
        labelTrackedRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = 1.1f, textCase = null, textDecoration = null),
        labelLooseSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        titleSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        posterSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 64.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.1f, letterSpacing = null, textCase = null, textDecoration = null),
        veil = 0.35f,
        bodyMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        labelLooseRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 2.0f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        iconLayer = 3.0f,
        family = listOf("IBM Plex Sans"),
        bodyRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 16.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.5f, letterSpacing = null, textCase = null, textDecoration = null),
        headlineSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        radius = TokensRadius(
            _12 = 12.0f,
            full = 999.0f,
            _4 = 4.0f,
        ),
        displayLargeSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 40.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.2f, letterSpacing = null, textCase = null, textDecoration = null),
        spaceMedium = 12.0f,
        spaceBig = 20.0f,
        giantSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 200.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.0f, letterSpacing = null, textCase = null, textDecoration = null),
        highlight = 1.5f,
        labelRegular = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 400, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        titleMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 22.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.2727f, letterSpacing = null, textCase = null, textDecoration = null),
        glyphBig = 32.0f,
        strokeBold = 4.0f,
        labelSemiBold = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 600, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        bodySmallMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 14.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.4286f, letterSpacing = null, textCase = null, textDecoration = null),
        connector = 0.55f,
        headlineMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 24.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        ghost = 0.18f,
        radiusRound = 999.0f,
        spaceSuperBig = 40.0f,
        medium = FontWeightToken(weight = 500, italic = false),
        labelMedium = TypographyToken(fontFamily = listOf("IBM Plex Sans"), fontSize = 12.0f, fontWeight = FontWeightToken(weight = 500, italic = false), lineHeight = 1.3333f, letterSpacing = null, textCase = null, textDecoration = null),
        link = TokensLink(
            colour = 0xFF4FD8C0,
        ),
        library = TokensLibrary(
            colorLink = 0xFF9A650F,
        ),
    )

    val default: Tokens = schemeStudioMonitorLight

    fun select(scheme: String): Tokens = when {
        scheme == "STUDIO_MONITOR light" -> schemeStudioMonitorLight
        scheme == "STUDIO_MONITOR dark" -> schemeStudioMonitorDark
        scheme == "PAPER_AND_INK light" -> schemePaperAndInkLight
        scheme == "PAPER_AND_INK dark" -> schemePaperAndInkDark
        scheme == "SIGNAL light" -> schemeSignalLight
        scheme == "SIGNAL dark" -> schemeSignalDark
        else -> schemeStudioMonitorLight
    }
}
