(ns penpot.mcp.html.script
  (:require
   [clojure.string :as str]))

(def ^:private helpers
  ["const generic = new Set(['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-sans-serif', 'ui-serif', 'ui-monospace', 'ui-rounded', '-apple-system', 'blinkmacsystemfont', 'emoji', 'math']);"
   "const fontCache = new Map();"
   "const substituted = new Set();"
   "const fallbackFont = () => penpot.fonts.findByName(args.fontFamily) ?? penpot.fonts.findById('sourcesanspro') ?? penpot.fonts.all[0];"
   "const resolveFont = (families) => {"
   "  if (fontCache.has(families)) return fontCache.get(families);"
   "  let font = null;"
   "  for (const raw of families.split(',')) {"
   "    const name = raw.trim();"
   "    if (!name || generic.has(name.toLowerCase())) continue;"
   "    font = penpot.fonts.findByName(name);"
   "    if (font) break;"
   "  }"
   "  if (!font) { font = fallbackFont(); substituted.add(families); }"
   "  fontCache.set(families, font);"
   "  return font;"
   "};"
   "const variantOf = (font, weight, style) => {"
   "  const same = font.variants.filter((v) => v.fontStyle === style);"
   "  const pool = same.length ? same : font.variants;"
   "  return pool.find((v) => v.fontWeight === weight)"
   "    ?? pool.slice().sort((a, b) => Math.abs(Number(a.fontWeight) - Number(weight)) - Math.abs(Number(b.fontWeight) - Number(weight)))[0];"
   "};"
   "let count = 0;"
   "const lines = [];"
   "const setLayout = (s, layout) => {"
   "  if (!layout) return;"
   "  const [top, right, bottom, left] = layout.padding;"
   "  if (layout.type === 'grid') {"
   "    const g = s.addGridLayout();"
   "    g.dir = layout.dir;"
   "    while (g.rows.length) g.removeRow(0);"
   "    while (g.columns.length) g.removeColumn(0);"
   "    for (const r of layout.rows) g.addRow(r.type, r.value);"
   "    for (const c of layout.columns) g.addColumn(c.type, c.value);"
   "    g.rowGap = layout.rowGap; g.columnGap = layout.columnGap;"
   "    g.topPadding = top; g.rightPadding = right; g.bottomPadding = bottom; g.leftPadding = left;"
   "    return;"
   "  }"
   "  const f = s.addFlexLayout();"
   "  f.dir = layout.dir; f.wrap = layout.wrap;"
   "  f.alignItems = layout.alignItems; f.justifyContent = layout.justifyContent; f.alignContent = layout.alignContent;"
   "  f.rowGap = layout.rowGap; f.columnGap = layout.columnGap;"
   "  f.topPadding = top; f.rightPadding = right; f.bottomPadding = bottom; f.leftPadding = left;"
   "};"
   "const setSelf = (s, self) => {"
   "  const lc = s.layoutChild;"
   "  if (!lc || !self) return;"
   "  if (self.absolute) lc.absolute = true;"
   "  if (self.width !== undefined) s.resize(self.width, s.height);"
   "  if (self.height !== undefined) s.resize(s.width, self.height);"
   "  lc.horizontalSizing = self.horizontalSizing;"
   "  lc.verticalSizing = self.verticalSizing;"
   "  if (self.alignSelf) lc.alignSelf = self.alignSelf;"
   "  const [mt, mr, mb, ml] = self.margin ?? [0, 0, 0, 0];"
   "  if (mt || mr || mb || ml) { lc.marginType = 'multiple'; lc.topMargin = mt; lc.rightMargin = mr; lc.bottomMargin = mb; lc.leftMargin = ml; }"
   "  for (const k of ['minWidth', 'maxWidth', 'minHeight', 'maxHeight']) if (self[k] !== undefined) lc[k] = self[k];"
   "};"
   "const attach = (s, node, parent) => {"
   "  if (!parent) return;"
   "  if (node.cell && parent.grid) {"
   "    parent.grid.appendChild(s, node.cell.row, node.cell.column);"
   "    if (s.layoutCell) { if (node.cell.rowSpan > 1) s.layoutCell.rowSpan = node.cell.rowSpan; if (node.cell.columnSpan > 1) s.layoutCell.columnSpan = node.cell.columnSpan; }"
   "  } else {"
   "    parent.appendChild(s);"
   "  }"
   "};"
   "const decorate = (s, node) => {"
   "  s.fills = node.fills ?? [];"
   "  if (node.strokes && node.strokes.length) s.strokes = node.strokes;"
   "  if (node.shadows && node.shadows.length) s.shadows = node.shadows;"
   "  if (node.opacity !== undefined && node.opacity !== 1) s.opacity = node.opacity;"
   "  const [tl, tr, br, bl] = node.radius ?? [0, 0, 0, 0];"
   "  if (tl || tr || br || bl) { s.borderRadiusTopLeft = tl; s.borderRadiusTopRight = tr; s.borderRadiusBottomRight = br; s.borderRadiusBottomLeft = bl; }"
   "};"
   "const textShape = (node, parent) => {"
   "  const full = node.runs.map((r) => r.text).join('');"
   "  const t = penpot.createText(full) ?? fail('create-failed', 'text');"
   "  t.name = node.name || 'text';"
   "  attach(t, node, parent);"
   "  t.growType = node.grow;"
   "  let start = 0;"
   "  for (const run of node.runs) {"
   "    const end = start + run.text.length;"
   "    if (end > start) {"
   "      const range = t.getRange(start, end);"
   "      const st = run.style;"
   "      const font = resolveFont(st.fontFamily);"
   "      font.applyToRange(range, variantOf(font, st.fontWeight, st.fontStyle));"
   "      range.fontSize = st.fontSize;"
   "      range.lineHeight = st.lineHeight;"
   "      range.letterSpacing = st.letterSpacing;"
   "      range.textTransform = st.textTransform;"
   "      range.textDecoration = st.textDecoration;"
   "      range.fills = st.fills;"
   "    }"
   "    start = end;"
   "  }"
   "  if (node.align && node.align !== 'left') t.align = node.align;"
   "  setSelf(t, node.self);"
   "  count += 1;"
   "  return t;"
   "};"
   "const imageShape = async (node, parent) => {"
   "  const src = node.src || '';"
   "  let image = null;"
   "  const data = src.match(/^data:([^;,]+)(;base64)?,(.*)$/s);"
   "  if (data) {"
   "    const raw = data[2] ? atob(data[3]) : decodeURIComponent(data[3]);"
   "    const bytes = new Uint8Array(raw.length);"
   "    for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);"
   "    image = await penpot.uploadMediaData(node.name || 'image', bytes, data[1]);"
   "  } else if (/^https?:\\/\\//.test(src)) {"
   "    image = await penpot.uploadMediaUrl(node.name || 'image', src);"
   "  }"
   "  if (!image) return null;"
   "  const r = penpot.createRectangle();"
   "  r.name = node.name || 'image';"
   "  r.resize(image.width, image.height);"
   "  r.fills = [{ fillOpacity: 1, fillImage: image }];"
   "  attach(r, node, parent);"
   "  setSelf(r, node.self);"
   "  count += 1;"
   "  return r;"
   "};"
   "const svgShape = (node, parent) => {"
   "  const g = penpot.createShapeFromSvg(node.markup);"
   "  if (!g) return null;"
   "  attach(g, node, parent);"
   "  setSelf(g, node.self);"
   "  count += 1;"
   "  return g;"
   "};"
   "const build = async (node, parent) => {"
   "  if (node.kind === 'text') return textShape(node, parent);"
   "  if (node.kind === 'image') return imageShape(node, parent);"
   "  if (node.kind === 'svg') return svgShape(node, parent);"
   "  const s = penpot.createBoard();"
   "  s.name = node.name || 'board';"
   "  attach(s, node, parent);"
   "  decorate(s, node);"
   "  s.clipContent = !!node.clip;"
   "  if (node.spacer) s.resize(1, 1);"
   "  setLayout(s, node.layout);"
   "  setSelf(s, node.self);"
   "  count += 1;"
   "  for (const child of node.children ?? []) await build(child, s);"
   "  for (const line of node.lines ?? []) lines.push({ parent: s, line });"
   "  return s;"
   "};"
   "const drawLine = ({ parent, line }) => {"
   "  const r = penpot.createRectangle();"
   "  r.name = 'border-' + line.side;"
   "  r.fills = [{ fillColor: line.color, fillOpacity: line.opacity }];"
   "  parent.appendChild(r);"
   "  if (r.layoutChild) r.layoutChild.absolute = true;"
   "  const horizontal = line.side === 'top' || line.side === 'bottom';"
   "  r.resize(horizontal ? parent.width : line.width, horizontal ? line.width : parent.height);"
   "  r.x = line.side === 'right' ? parent.x + parent.width - line.width : parent.x;"
   "  r.y = line.side === 'bottom' ? parent.y + parent.height - line.width : parent.y;"
   "  r.constraintsHorizontal = horizontal ? 'leftright' : line.side;"
   "  r.constraintsVertical = horizontal ? line.side : 'topbottom';"
   "  count += 1;"
   "};"])

(def frame-body
  (str/join
   "\n"
   (concat
    helpers
    ["await focusPage(args.pageId);"
     "const existing = penpot.currentPage.root.children.map((c) => c.y + c.height);"
     "const y = args.y ?? (existing.length ? Math.max(...existing) + 200 : 0);"
     "const block = penpot.history.undoBlockBegin();"
     "let root;"
     "try {"
     "  const node = args.node;"
     "  root = penpot.createBoard();"
     "  root.name = node.name || 'frame';"
     "  root.x = args.x; root.y = y;"
     "  root.resize(node.width, node.height ?? 100);"
     "  decorate(root, node);"
     "  root.clipContent = !!node.clip;"
     "  setLayout(root, node.layout);"
     "  if (root.flex) { root.flex.horizontalSizing = 'fix'; root.flex.verticalSizing = node.sizing.vertical; }"
     "  count += 1;"
     "  for (const child of node.children ?? []) await build(child, root);"
     "  for (const line of node.lines ?? []) lines.push({ parent: root, line });"
     "  markChanged();"
     "  if (lines.length) { await penpot.waitForLayoutUpdate(10000); for (const l of lines) drawLine(l); }"
     "} finally {"
     "  penpot.history.undoBlockFinish(block);"
     "}"
     "return { boardId: root.id, name: root.name, pageId: penpot.currentPage.id, x: root.x, y: root.y, width: root.width, height: root.height,"
     "         shapes: count, substitutedFonts: [...substituted] };"])))

(def page-body
  (str/join
   "\n"
   ["const page = penpot.createPage();"
    "page.name = args.name;"
    "markChanged();"
    "await waitFor(() => penpotUtils.getPageById(page.id));"
    "return { pageId: page.id, name: page.name };"]))
