(ns penpot.mcp.html.script
  (:require
   [clojure.string :as str]))

(def ^:private helpers
  ["const generic = new Set(['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-sans-serif', 'ui-serif', 'ui-monospace', 'ui-rounded', '-apple-system', 'blinkmacsystemfont', 'emoji', 'math']);"
   "const fontCache = new Map();"
   "const substituted = new Set();"
   "const fallbackFont = () => penpot.fonts.findByName(args.fontFamily) ?? penpot.fonts.findById('sourcesanspro') ?? penpot.fonts.all[0];"
   "const resolveFont = (families) => {"
   "  if (fontCache.has(families)) return fontCache.get(families);"
   "  let font = null;"
   "  for (const raw of families.split(',')) {"
   "    const name = raw.trim();"
   "    if (!name || generic.has(name.toLowerCase())) continue;"
   "    font = penpot.fonts.findByName(name);"
   "    if (font) break;"
   "  }"
   "  if (!font) { font = fallbackFont(); substituted.add(families); }"
   "  fontCache.set(families, font);"
   "  return font;"
   "};"
   "const variantOf = (font, weight, style) => {"
   "  const same = font.variants.filter((v) => v.fontStyle === style);"
   "  const pool = same.length ? same : font.variants;"
   "  return pool.find((v) => v.fontWeight === weight)"
   "    ?? pool.slice().sort((a, b) => Math.abs(Number(a.fontWeight) - Number(weight)) - Math.abs(Number(b.fontWeight) - Number(weight)))[0];"
   "};"
   "let count = 0;"
   "const put = (o, k, v) => { if (v !== undefined && v !== null && o[k] !== v) o[k] = v; };"
   "const putList = (o, k, v) => { if (v && JSON.stringify(o[k] ?? []) !== JSON.stringify(v)) o[k] = v; };"
   "const setLayout = (s, layout) => {"
   "  if (!layout) return;"
   "  const [top, right, bottom, left] = layout.padding;"
   "  if (layout.type === 'grid') {"
   "    const g = s.addGridLayout();"
   "    put(g, 'dir', layout.dir);"
   "    while (g.rows.length) g.removeRow(0);"
   "    while (g.columns.length) g.removeColumn(0);"
   "    for (const r of layout.rows) g.addRow(r.type, r.value);"
   "    for (const c of layout.columns) g.addColumn(c.type, c.value);"
   "    put(g, 'rowGap', layout.rowGap); put(g, 'columnGap', layout.columnGap);"
   "    put(g, 'topPadding', top); put(g, 'rightPadding', right); put(g, 'bottomPadding', bottom); put(g, 'leftPadding', left);"
   "    return;"
   "  }"
   "  const f = s.addFlexLayout();"
   "  put(f, 'dir', layout.dir); put(f, 'wrap', layout.wrap);"
   "  put(f, 'alignItems', layout.alignItems); put(f, 'justifyContent', layout.justifyContent); put(f, 'alignContent', layout.alignContent);"
   "  put(f, 'rowGap', layout.rowGap); put(f, 'columnGap', layout.columnGap);"
   "  put(f, 'topPadding', top); put(f, 'rightPadding', right); put(f, 'bottomPadding', bottom); put(f, 'leftPadding', left);"
   "};"
   "const setSelf = (s, self) => {"
   "  const lc = s.layoutChild;"
   "  if (!lc || !self) return;"
   "  if (self.absolute) put(lc, 'absolute', true);"
   "  if (self.width !== undefined) s.resize(self.width, s.height);"
   "  if (self.height !== undefined) s.resize(s.width, self.height);"
   "  put(lc, 'horizontalSizing', self.horizontalSizing);"
   "  put(lc, 'verticalSizing', self.verticalSizing);"
   "  put(lc, 'alignSelf', self.alignSelf);"
   "  const [mt, mr, mb, ml] = self.margin ?? [0, 0, 0, 0];"
   "  if (mt || mr || mb || ml) { put(lc, 'marginType', 'multiple'); put(lc, 'topMargin', mt); put(lc, 'rightMargin', mr); put(lc, 'bottomMargin', mb); put(lc, 'leftMargin', ml); }"
   "  for (const k of ['minWidth', 'maxWidth', 'minHeight', 'maxHeight']) put(lc, k, self[k]);"
   "};"
   "const attach = (s, node, parent) => {"
   "  if (!parent) return;"
   "  if (node.cell && parent.grid) {"
   "    parent.grid.appendChild(s, node.cell.row, node.cell.column);"
   "    if (s.layoutCell) { if (node.cell.rowSpan > 1) s.layoutCell.rowSpan = node.cell.rowSpan; if (node.cell.columnSpan > 1) s.layoutCell.columnSpan = node.cell.columnSpan; }"
   "  } else {"
   "    parent.appendChild(s);"
   "  }"
   "};"
   "const decorate = (s, node) => {"
   "  putList(s, 'fills', node.fills ?? []);"
   "  if (node.strokes && node.strokes.length) putList(s, 'strokes', node.strokes);"
   "  if (node.shadows && node.shadows.length) putList(s, 'shadows', node.shadows);"
   "  if (node.opacity !== undefined && node.opacity !== 1) put(s, 'opacity', node.opacity);"
   "  const [tl, tr, br, bl] = node.radius ?? [0, 0, 0, 0];"
   "  if (tl || tr || br || bl) { put(s, 'borderRadiusTopLeft', tl); put(s, 'borderRadiusTopRight', tr); put(s, 'borderRadiusBottomRight', br); put(s, 'borderRadiusBottomLeft', bl); }"
   "};"
   "const textShape = (node, parent) => {"
   "  const full = node.runs.map((r) => r.text).join('');"
   "  const t = penpot.createText(full) ?? fail('create-failed', 'text');"
   "  t.name = node.name || 'text';"
   "  attach(t, node, parent);"
   "  put(t, 'growType', node.grow);"
   "  let start = 0;"
   "  for (const run of node.runs) {"
   "    const end = start + run.text.length;"
   "    if (end > start) {"
   "      const range = t.getRange(start, end);"
   "      const st = run.style;"
   "      const font = resolveFont(st.fontFamily);"
   "      const variant = variantOf(font, st.fontWeight, st.fontStyle);"
   "      if (range.fontId !== font.fontId || range.fontVariantId !== variant.fontVariantId) font.applyToRange(range, variant);"
   "      put(range, 'fontSize', st.fontSize);"
   "      put(range, 'lineHeight', st.lineHeight);"
   "      put(range, 'letterSpacing', st.letterSpacing);"
   "      if (st.textTransform !== 'none' || (range.textTransform && range.textTransform !== 'none')) put(range, 'textTransform', st.textTransform);"
   "      if (st.textDecoration !== 'none' || (range.textDecoration && range.textDecoration !== 'none')) put(range, 'textDecoration', st.textDecoration);"
   "      putList(range, 'fills', st.fills);"
   "    }"
   "    start = end;"
   "  }"
   "  if (node.align && node.align !== 'left') put(t, 'align', node.align);"
   "  setSelf(t, node.self);"
   "  count += 1;"
   "  return t;"
   "};"
   "const imageShape = async (node, parent) => {"
   "  const src = node.src || '';"
   "  let image = null;"
   "  const data = src.match(/^data:([^;,]+)(;base64)?,(.*)$/s);"
   "  if (data) {"
   "    const raw = data[2] ? atob(data[3]) : decodeURIComponent(data[3]);"
   "    const bytes = new Uint8Array(raw.length);"
   "    for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);"
   "    image = await penpot.uploadMediaData(node.name || 'image', bytes, data[1]);"
   "  } else if (/^https?:\\/\\//.test(src)) {"
   "    image = await penpot.uploadMediaUrl(node.name || 'image', src);"
   "  }"
   "  if (!image) return null;"
   "  const r = penpot.createRectangle();"
   "  r.name = node.name || 'image';"
   "  r.resize(image.width, image.height);"
   "  r.fills = [{ fillOpacity: 1, fillImage: image }];"
   "  attach(r, node, parent);"
   "  setSelf(r, node.self);"
   "  count += 1;"
   "  return r;"
   "};"
   "const svgShape = (node, parent) => {"
   "  const g = penpot.createShapeFromSvg(node.markup);"
   "  if (!g) return null;"
   "  attach(g, node, parent);"
   "  setSelf(g, node.self);"
   "  count += 1;"
   "  return g;"
   "};"
   "const build = async (node, parent) => {"
   "  if (node.kind === 'text') return textShape(node, parent);"
   "  if (node.kind === 'image') return imageShape(node, parent);"
   "  if (node.kind === 'svg') return svgShape(node, parent);"
   "  const s = penpot.createBoard();"
   "  s.name = node.name || 'board';"
   "  attach(s, node, parent);"
   "  decorate(s, node);"
   "  put(s, 'clipContent', !!node.clip);"
   "  if (node.spacer) s.resize(1, 1);"
   "  setLayout(s, node.layout);"
   "  setSelf(s, node.self);"
   "  count += 1;"
   "  if (node.key) ids[node.key] = s.id;"
   "  for (const child of node.children ?? []) await build(child, s);"
   "  return s;"
   "};"
   "const ids = Object.assign({}, args.ids);"])

(def frame-body
  (str/join
   "\n"
   (concat
    helpers
    ["await focusPage(args.pageId);"
     "let rootId = args.rootId;"
     "const createRoot = (node) => {"
     "  const existing = penpot.currentPage.root.children.map((c) => c.y + c.height);"
     "  const root = penpot.createBoard();"
     "  root.name = node.name || 'frame';"
     "  root.x = args.x;"
     "  root.y = args.y ?? (existing.length ? Math.max(...existing) + 200 : 0);"
     "  root.resize(node.width, node.height ?? 100);"
     "  decorate(root, node);"
     "  put(root, 'clipContent', !!node.clip);"
     "  setLayout(root, node.layout);"
     "  if (root.flex) { put(root.flex, 'horizontalSizing', 'fix'); put(root.flex, 'verticalSizing', node.sizing.vertical); }"
     "  if (node.key) ids[node.key] = root.id;"
     "  count += 1;"
     "  return root;"
     "};"
     "const block = penpot.history.undoBlockBegin();"
     "try {"
     "  for (const unit of args.units) {"
     "    if (unit.root) {"
     "      const root = createRoot(unit.node);"
     "      rootId = root.id;"
     "      for (const child of unit.node.children ?? []) await build(child, root);"
     "    } else {"
     "      const parent = penpot.currentPage.getShapeById(ids[unit.parent]) ?? fail('shape-not-found', unit.parent);"
     "      await build(unit.node, parent);"
     "    }"
     "  }"
     "  markChanged();"
     "} finally {"
     "  penpot.history.undoBlockFinish(block);"
     "}"
     "const root = penpot.currentPage.getShapeById(rootId) ?? fail('shape-not-found', rootId);"
     "return { ids, boardId: root.id, name: root.name, pageId: penpot.currentPage.id, x: root.x, y: root.y, width: root.width, height: root.height,"
     "         shapes: count, substitutedFonts: [...substituted] };"])))

(def lines-body
  (str/join
   "\n"
   ["await focusPage(args.pageId);"
    "const pairs = args.lines.map((line) => [line, penpot.currentPage.getShapeById(args.ids[line.key])]).filter(([, p]) => p);"
    "const boxes = () => JSON.stringify(pairs.map(([, p]) => [p.x, p.y, p.width, p.height]));"
    "let previous = '';"
    "for (let i = 0; i < 30; i++) { const now = boxes(); if (now === previous) break; previous = now; await settle(100); }"
    "const block = penpot.history.undoBlockBegin();"
    "try {"
    "  for (const [line, parent] of pairs) {"
    "    const r = penpot.createRectangle();"
    "    r.name = 'border-' + line.side;"
    "    r.fills = [{ fillColor: line.color, fillOpacity: line.opacity }];"
    "    parent.appendChild(r);"
    "    if (r.layoutChild) r.layoutChild.absolute = true;"
    "    const horizontal = line.side === 'top' || line.side === 'bottom';"
    "    r.resize(horizontal ? parent.width : line.width, horizontal ? line.width : parent.height);"
    "    r.x = line.side === 'right' ? parent.x + parent.width - line.width : parent.x;"
    "    r.y = line.side === 'bottom' ? parent.y + parent.height - line.width : parent.y;"
    "    r.constraintsHorizontal = horizontal ? 'leftright' : line.side;"
    "    r.constraintsVertical = horizontal ? line.side : 'topbottom';"
    "  }"
    "  if (pairs.length) markChanged();"
    "} finally {"
    "  penpot.history.undoBlockFinish(block);"
    "}"
    "return { lines: pairs.length };"]))

(def remove-body
  (str/join
   "\n"
   ["const s = penpotUtils.findShapeById(args.shapeId);"
    "if (s) { await focusShape(args.shapeId); penpot.currentPage.getShapeById(args.shapeId)?.remove(); markChanged(); }"
    "return { removed: !!s };"]))

(def page-body
  (str/join
   "\n"
   ["const page = penpot.createPage();"
    "page.name = args.name;"
    "markChanged();"
    "await waitFor(() => penpotUtils.getPageById(page.id));"
    "return { pageId: page.id, name: page.name };"]))
